package com.hbm.forgefluid;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.hbm.forgefluid.FluidTypeHandler.FluidProperties;
import com.hbm.forgefluid.FluidTypeHandler.FluidTrait;
import com.hbm.inventory.EngineRecipes;
import com.hbm.inventory.EngineRecipes.FuelGrade;
import com.hbm.inventory.FluidCombustionRecipes;
import com.hbm.lib.RefStrings;
import com.hbm.render.misc.EnumSymbol;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

/**
 * Declarative fluid definition. Everything about a fluid - registry name, translation key, textures, color,
 * temperature, hazard card, flag and valued traits, engine fuel - is stated once through the fluent builder.
 * All registration (Forge fluid registry, hazard properties, combustion, engine fuel) is generated by iterating
 * {@link #ALL}, so adding a fluid never means editing several separate registry methods again.
 *
 * Valued traits are only stored when non-zero, so an omitted or zero characteristic is genuinely absent - e.g.
 * a fluid without a COMBUSTION_TU value never shows up as a combustion fuel at all.
 */
public class HbmFluid {

	public static final List<HbmFluid> ALL = new ArrayList<HbmFluid>();

	private final String name;
	private String translationKey;
	private String stillTexture;
	private String flowingTexture;
	private int color = 0xFFFFFF;
	private Integer temperature;

	private int poison = 0;
	private int flammability = 0;
	private int reactivity = 0;
	private float dfcFuel = 0;
	private EnumSymbol symbol = EnumSymbol.NONE;

	private final List<FluidTrait> flags = new ArrayList<FluidTrait>();
	private final Map<FluidTrait, Double> values = new HashMap<FluidTrait, Double>();

	private FuelGrade fuelGrade;
	private long fuelPower;

	private Fluid fluid;

	private HbmFluid(String name) {
		this.name = name;
	}

	public static HbmFluid builder(String name) {
		return new HbmFluid(name);
	}

	public HbmFluid translationKey(String key) { this.translationKey = key; return this; }
	public HbmFluid textures(String still, String flowing) { this.stillTexture = still; this.flowingTexture = flowing; return this; }
	public HbmFluid color(int rgb) { this.color = rgb; return this; }
	public HbmFluid temperature(int celsius) { this.temperature = celsius + 273; return this; }

	public HbmFluid props(int poison, int flammability, int reactivity, EnumSymbol symbol) {
		this.poison = poison;
		this.flammability = flammability;
		this.reactivity = reactivity;
		this.symbol = symbol;
		return this;
	}

	public HbmFluid dfc(float efficiency) { this.dfcFuel = efficiency; return this; }

	//flag trait (corrosive, amat, ...)
	public HbmFluid trait(FluidTrait trait) { flags.add(trait); return this; }
	//valued trait (combustion tu, rtg efficiency, ...); zero is dropped so it never counts as present
	public HbmFluid trait(FluidTrait trait, double value) { if(value != 0) values.put(trait, value); return this; }

	//engine (diesel/generator) fuel: grade + power; zero power = not a fuel
	public HbmFluid fuel(FuelGrade grade, long power) { this.fuelGrade = grade; this.fuelPower = power; return this; }

	//Creates the Forge fluid (textures/lang by convention unless overridden) and enlists it. Assign the returned
	//Fluid to the existing ModForgeFluids static field so all current references keep working.
	public Fluid build() {
		String still = stillTexture != null ? stillTexture : "blocks/forgefluid/" + name + "_still";
		String flow = flowingTexture != null ? flowingTexture : "blocks/forgefluid/" + name + "_flowing";

		fluid = new Fluid(name,
				new ResourceLocation(RefStrings.MODID, still),
				new ResourceLocation(RefStrings.MODID, flow),
				new Color(color));

		if(temperature != null)
			fluid.setTemperature(temperature);
		if(translationKey != null)
			fluid.setUnlocalizedName(translationKey);

		ALL.add(this);
		return fluid;
	}

	public Fluid getFluid() { return fluid; }

	// --- registration: called from the existing init hooks, generated from ALL ---

	public static void registerAllToForge() {
		for(HbmFluid f : ALL)
			if(!FluidRegistry.registerFluid(f.fluid))
				f.fluid = FluidRegistry.getFluid(f.name);
	}

	public static void applyAllProperties() {
		for(HbmFluid f : ALL) {
			FluidProperties p = new FluidProperties(f.poison, f.flammability, f.reactivity, f.dfcFuel, f.symbol,
					f.flags.toArray(new FluidTrait[0]));
			p.traitValues.putAll(f.values);
			FluidTypeHandler.registerProperties(f.fluid.getName(), p);
		}
	}

	public static void applyAllFuels() {
		for(HbmFluid f : ALL) {
			double tu = f.values.containsKey(FluidTrait.COMBUSTION_TU) ? f.values.get(FluidTrait.COMBUSTION_TU) : 0;
			if(tu > 0)
				FluidCombustionRecipes.addBurnableFluid(f.fluid, (int) tu);
			if(f.fuelGrade != null && f.fuelPower > 0)
				EngineRecipes.addFuel(f.fluid, f.fuelGrade, f.fuelPower);
		}
	}
}
